# Further Preparing Data

In [37]:
import numpy as np
import pandas as pd

In [38]:
raw_df = pd.read_csv("Cleaned_HackathonData2024.csv")

In [39]:
raw_df

,Well ID,Avg Pump Difference,Area,Lateral Length,Fluid System,TVD,Development Strategy,DELAYED,BOUND_CODE,PARENT_CODEV_1050_WELL_COUNT,...,CODEV_3000_AVG_TVD_DIST,CODEV_3000_AVG_WELL_AGE,CODEV_3000_MEDIAN_WELL_AGE,CODEV_3000_WELL_COUNT,Pressure Gradient (psi/ft) new,Soak Time,Avg Open Pressure,SD Open Pressure,Avg Close Pressure,SD Close Pressure
0,1,-0.93,Acadia,10300,Campbell,10415.0,Coke,1,11100000,2,...,4,0.0,0.0,1,0.593758,34,3304.124833,261.7,2719.898438,472.4
1,2,-8.45,Acadia,10300,Campbell,10415.0,Coke,1,11100000,2,...,4,0.0,0.0,1,0.597059,67,3301.199254,255.9,2934.885325,747.4
2,3,8.70,Arches,11000,Campbell,8470.0,Orange Crush,0,101111,6,...,682,4.5,0.0,11,0.516873,34,2774.407080,184.8,1589.948673,596.9
3,4,NaN,Arches,11000,Campbell,10555.0,Coke,1,11110000,1,...,4,0.0,0.0,1,0.501287,30,2653.539415,206.7,1304.162878,551.5
4,6,-4.34,Big Bend,12300,Campbell,10355.0,Coke,1,11110000,0,...,1410,21.5,28.5,4,0.565200,21,2963.567911,232.0,2063.408619,517.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,349,4.09,Grand Canyon,10300,Williams,8350.0,Orange Crush,0,11001000,3,...,313,0.7,1.0,3,0.568531,108,2928.200185,238.2,2381.445271,525.2
340,350,37.96,Grand Canyon,10300,Williams,8350.0,Orange Crush,0,11001000,3,...,313,0.7,1.0,3,0.554243,114,2747.262178,217.9,2309.826087,653.4
341,353,68.21,Mount Rainier,7700,Williams,10365.0,Coke,1,11111000,4,...,10,0.0,0.0,1,0.512640,245,3056.211966,212.0,2032.922355,533.8
342,354,29.18,Mount Rainier,7700,Williams,10300.0,Coke,1,11111000,3,...,12,0.0,0.0,1,0.530874,315,2969.985594,230.1,1821.549742,314.5
343,356,30.42,Mount Rainier,7700,Williams,10355.0,Coke,1,11111001,3,...,11,0.0,0.0,1,0.530376,355,2966.579531,158.1,1818.192820,360.6

In [40]:
raw_df.columns.tolist()

['Well ID',
 'Avg Pump Difference',
 'Area',
 'Lateral Length',
 'Fluid System',
 'TVD',
 'Development Strategy',
 'DELAYED',
 'BOUND_CODE',
 'PARENT_CODEV_1050_WELL_COUNT',
 'PARENT_IN_ZONE_MIN_HYPOT',
 'PARENT_1050_WELL_COUNT',
 'PARENT_3000_AVG_HYPOT_DIST',
 'PARENT_3000_WELL_COUNT',
 'CODEV_IN_ZONE_MIN_HYPOT',
 'CODEV_1050_WELL_COUNT',
 'CODEV_3000_AVG_HYPOT_DIST',
 'CODEV_3000_AVG_TVD_DIST',
 'CODEV_3000_AVG_WELL_AGE',
 'CODEV_3000_MEDIAN_WELL_AGE',
 'CODEV_3000_WELL_COUNT',
 'Pressure Gradient (psi/ft) new',
 'Soak Time',
 'Avg Open Pressure',
 'SD Open Pressure',
 'Avg Close Pressure',
 'SD Close Pressure']

In [41]:
def createBound(row, idx):
    bound = row["BOUND_CODE"]
    bound = "%08d" % bound
    
    side_index = [0, 4]
    above_index = [1, 2, 3]
    below_index = [5, 6, 7]
    side = sum([int(bound[i]) for i in side_index])
    above = sum([int(bound[i]) for i in above_index])
    below = sum([int(bound[i]) for i in below_index])
    
    if idx == 0:
        return side
    elif idx == 1:
        return above
    else:
        return below
    
    
raw_df["side"] = raw_df.apply(lambda x: createBound(x, 0), axis=1)
raw_df["above"] = raw_df.apply(lambda x: createBound(x, 1), axis=1)
raw_df["below"] = raw_df.apply(lambda x: createBound(x, 2), axis=1)

In [42]:
raw_df = raw_df.drop(["BOUND_CODE"], axis = 1)

In [43]:
cat_vars = [
    "Area",
    "Fluid System",
    "Development Strategy"
]

for col in cat_vars:
    temp = pd.get_dummies(raw_df[col], prefix=col)
    raw_df[temp.columns] = temp[temp.columns]
    raw_df = raw_df.drop([col], axis = 1)

In [44]:
raw_df

,Well ID,Avg Pump Difference,Lateral Length,TVD,DELAYED,PARENT_CODEV_1050_WELL_COUNT,PARENT_IN_ZONE_MIN_HYPOT,PARENT_1050_WELL_COUNT,PARENT_3000_AVG_HYPOT_DIST,PARENT_3000_WELL_COUNT,...,Fluid System_Campbell,Fluid System_Williams,Fluid System_Young,Development Strategy_Coke,Development Strategy_Dr Pepper,Development Strategy_Mountain Dew,Development Strategy_Orange Crush,Development Strategy_Pepsi,Development Strategy_Pibb Extra,Development Strategy_Sprite
0,1,-0.93,10300,10415.0,1,2,1195.286743,2,2071.0,12,...,1,0,0,1,0,0,0,0,0,0
1,2,-8.45,10300,10415.0,1,2,1195.286743,2,2071.0,12,...,1,0,0,1,0,0,0,0,0,0
2,3,8.70,11000,8470.0,0,6,2882.384033,0,2492.0,6,...,1,0,0,0,0,0,1,0,0,0
3,4,NaN,11000,10555.0,1,1,1059.568848,0,2378.0,20,...,1,0,0,1,0,0,0,0,0,0
4,6,-4.34,12300,10355.0,1,0,2763.000000,0,2464.0,13,...,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,349,4.09,10300,8350.0,0,3,1348.000000,0,2168.0,9,...,0,1,0,0,0,0,1,0,0,0
340,350,37.96,10300,8350.0,0,3,1348.000000,0,2168.0,9,...,0,1,0,0,0,0,1,0,0,0
341,353,68.21,7700,10365.0,1,4,1508.000000,3,2213.0,35,...,0,1,0,1,0,0,0,0,0,0
342,354,29.18,7700,10300.0,1,3,1266.686035,3,1923.0,24,...,0,1,0,1,0,0,0,0,0,0
343,356,30.42,7700,10355.0,1,3,2854.000000,3,2151.0,47,...,0,1,0,1,0,0,0,0,0,0

In [45]:
raw_df.to_csv("Final_dataset.csv")